name: My first workflow

on: push 

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "My first GithubActions"

            - name: List files
              run: ls
            
            - name: Read file
              run: cat Readme.md
            