name: generate the ascii

on: push 

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List repo files
              run: ls -ltra
            - name: executing the commands as script
              run: |
                chmod +X  .github/workflows/ascii.script.sh
                sudo ./.github/workflows/ascii.script.sh
