name: generate the ascii

on: push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a dragon --" >> dragon.txt

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text
          path: dragon.txt

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-text
          path: .

      - name: Test file exists 
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    needs: [build_job1, test_job2]
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-text
          path: .

      - name: Read the file
        run: cat dragon.txt

      - name: Deploy
        run: echo "This is the deploy job"
